### ISSUE TITLE
Shows "null" entries

### ISSUE THREAD

**Issue by fidian** [JumpMaster/PebbleAuth#10] opened 2015-01-13 13:11 UTC
![pebble-screenshot_2015-01-13_07-11-08](https://cloud.githubusercontent.com/assets/428348/5721132/5d03e932-9af3-11e4-941d-c9ef0a41d9f1.png)

Not sure how I got this, but I'm pretty sure it shouldn't have been saved to the watch.

**Comment by JumpMaster** [comment] 2015-01-14 07:56
I've seen this issue but have not been able to reproduce it. Without reproducing it I cannot implement a fix.

On 13 Jan 2015 13:13, Tyler Akins <notifications@github.com> wrote:

[pebble-screenshot_2015-01-13_07-11-08]<https://cloud.githubusercontent.com/assets/428348/5721132/5d03e932-9af3-11e4-941d-c9ef0a41d9f1.png>

Not sure how I got this, but I'm pretty sure it shouldn't have been saved to the watch.

**Comment by LinkChef** [comment] 2015-01-31 22:42
Hello, I was having this issue as well.  However, I discovered that the null error was only caused by second style of font that is within the app.  I tested with styles 1, 3, and 4 with no "null" entry error.

My theory is that the font that supports up to 20 characters for names has an issue keeping entries correct because it is special in that regard.  Would this be a possible theory?

Please comment back here or message me if you'd like more data.  Thank you for your app!

**Comment by fidian** [comment] 2015-02-25 19:08
I've not reconfigured my app after I added my three tokens and filed the initial bug report.  At that time I had 3 null entries.  Now I am up to 7.  I have the app assigned to a quick launch button (long press the top button) and I end up on the first key.  Then I want to cycle up so I press the top button and I end up on "null".  I press up 6 more times and still have null.  Pressing up a 7th time gets me past the null entries.

I don't know what's going on, but it appears to solely relate to just the operation of the watch.

How can I remove the null entries?  I would really like to eliminate them even if you don't know what's causing them.

**Comment by JumpMaster** [comment] 2015-02-25 19:48
The config page has a "DELETE ALL" button which will do exactly that.  Including any errored entries.  So it sounds like there's either some corruption/entires appearing on the watch. Or there is an errored code on the phone which gets pulled to the watch app.  How many entries does the config page say you have available?  If you only have three code I'd hope it says 13 spaces available.

**Comment by JumpMaster** [comment] 2015-02-25 19:54
I've got an idea. Give me a few days!

On 25 Feb 2015 19:08, Tyler Akins <notifications@github.com> wrote:

I've not reconfigured my app after I added my three tokens and filed the initial bug report. At that time I had 3 null entries. Now I am up to 7. I have the app assigned to a quick launch button (long press the top button) and I end up on the first key. Then I want to cycle up so I press the top button and I end up on "null". I press up 6 more times and still have null. Pressing up a 7th time gets me past the null entries.

I don't know what's going on, but it appears to solely relate to just the operation of the watch.

How can I remove the null entries? I would really like to eliminate them even if you don't know what's causing them.

**Comment by fidian** [comment] 2015-02-25 20:12
To answer the questions from earlier, the config page says I have 13 spaces remaining.  I'll continue this in the email discussion.

**Comment by fidian** [comment] 2015-02-25 20:16
I would love to be a guinea pig.  I'm a good one too as I'm able to happily
push apps into my pebble.  Maybe I should peek around in the code to see
what's going on and compile a few test versions myself?

I am running the latest firmware.  I was running the beta firmware there
before 2.9 was officially released.  It is possible that the betas operated
differently or that things go a bit wonky when I restart the watch.

What bothers me is that it doesn't show 13 empty entries.  Just a few.

--
Tyler Akins

**Comment by fidian** [comment] 2015-02-25 22:48
Made progress and identified a way to make the null entries happen.  I have three codes.  When I selected another code then pressed the select button (middle button) and followed by √ (top button) a null entry was added.  The author has a fix and is testing.  Let's make sure to give him a few days before we pester for an update.  :-)

**Comment by JumpMaster** [comment] 2015-03-02 19:31
Version 1.6 released which fixed the null issue.

**Closed by JumpMaster** 2015-03-02 19:31 UTC
